/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraestadistica;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author ulise
 */
public class PantallaResultados extends javax.swing.JFrame {

   private static Calculos calculo;
    public PantallaResultados(Calculos calculo) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/calculadora.png")).getImage());
        this.calculo = calculo;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        llenarTabla();
        lblMedia.setText(lblMedia.getText() + " "+ String.format("%3.3f", calculo.getMedia()));
        lblMediana.setText(lblMediana.getText() + " "+ String.format("%3.3f", calculo.getMediana()));
        lblModa.setText(lblModa.getText() + " "+ String.format("%3.3f", calculo.getModa()));
        lblDesviacion.setText(lblDesviacion.getText() + " "+ String.format("%3.3f", calculo.getDesEs()));
        
        
                
                
    }
    
    private void llenarTabla()
    {
        DefaultTableModel mD = new DefaultTableModel(new String[]{"Clase", "Limite inferior", "Limite superior", "Limite inferior exacto", "Limite superior exacto", "Frecuencia absoluta", "Frecuecia acumulada", "Frecuencia relativa", "Marca de clase"} , calculo.getClases().size()); 
        tblTabla.setModel(mD);
        TableModel modeloDatos = tblTabla.getModel();
        for(int i = 0; i < calculo.getClases().size(); i++)
        {
            modeloDatos.setValueAt(calculo.getClases().get(i).getClase(), i, 0);
            modeloDatos.setValueAt(calculo.getClases().get(i).getLimInf(), i, 1);
            modeloDatos.setValueAt(calculo.getClases().get(i).getLimSup(), i, 2);
            modeloDatos.setValueAt(calculo.getClases().get(i).getLimInfEx(), i, 3);
            modeloDatos.setValueAt(calculo.getClases().get(i).getLimSupEx(), i, 4);
            modeloDatos.setValueAt(calculo.getClases().get(i).getFrec(), i, 5);
            modeloDatos.setValueAt(calculo.getClases().get(i).getFrecAcum(), i, 6);
            modeloDatos.setValueAt(String.format("%3.3f", calculo.getClases().get(i).getFrecRel()), i, 7);
            modeloDatos.setValueAt(calculo.getClases().get(i).getMarcaCla(), i, 8);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResultados = new javax.swing.JPanel();
        lblMedia = new javax.swing.JLabel();
        lblMediana = new javax.swing.JLabel();
        lblModa = new javax.swing.JLabel();
        lblDesviacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlResultados.setBackground(new java.awt.Color(204, 204, 255));

        lblMedia.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblMedia.setText("Media:");

        lblMediana.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblMediana.setText("Mediana:");

        lblModa.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblModa.setText("Moda:");

        lblDesviacion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDesviacion.setText("Desviación estándar:");

        tblTabla.setBackground(new java.awt.Color(240, 240, 240));
        tblTabla.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clase", "Límite inferior", "Límite superior", "Límite inferior exacto", "Límite superior exacto", "Frecuencia absoluta", "Frecuencia acumulada", "Frecuencia relativa", "Marca de clase"
            }
        ));
        jScrollPane2.setViewportView(tblTabla);

        javax.swing.GroupLayout pnlResultadosLayout = new javax.swing.GroupLayout(pnlResultados);
        pnlResultados.setLayout(pnlResultadosLayout);
        pnlResultadosLayout.setHorizontalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosLayout.createSequentialGroup()
                .addGroup(pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResultadosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(lblMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(lblModa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(lblDesviacion, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlResultadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        pnlResultadosLayout.setVerticalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesviacion)
                    .addComponent(lblModa)
                    .addComponent(lblMediana)
                    .addComponent(lblMedia))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDesviacion;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblMediana;
    private javax.swing.JLabel lblModa;
    private javax.swing.JPanel pnlResultados;
    private javax.swing.JTable tblTabla;
    // End of variables declaration//GEN-END:variables
}
