/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package calculadoraestadistica;

import java.awt.Cursor;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
public class PantallaAgregar extends javax.swing.JFrame {

    /** Creates new form PantallaAgregar */
    private Calculos calcu = new Calculos();
    public PantallaAgregar() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/calculadora.png")).getImage());
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        btnAgregar.setCursor(new Cursor (Cursor.HAND_CURSOR));
        btnCalcular.setCursor(new Cursor (Cursor.HAND_CURSOR));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblIngresar = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtAgregar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        lblIngresar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblIngresar.setText("Ingrese número:");

        btnCalcular.setBackground(new java.awt.Color(204, 255, 204));
        btnCalcular.setText("Calcular");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 204, 204));
        btnAgregar.setText("Agregar\n");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtAgregar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngresar)
                            .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnCalcular)
                        .addGap(44, 44, 44)
                        .addComponent(btnAgregar)))
                .addGap(0, 111, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnAgregar))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(txtAgregar.getText().equals(""))
        {
            
        }
        else
        {
            try
            {
                calcu.agregar(Integer.parseInt(txtAgregar.getText()));
                txtAgregar.setText("");
                txtAgregar.grabFocus();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "El número introducido no es un entero.", "ERROR", HEIGHT);
                txtAgregar.setText("");
                txtAgregar.grabFocus();
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try
        {
            calcu.rellenarTabla();
            this.setVisible(false);
            PantallaResultados pr = new PantallaResultados(calcu);
            pr.setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Debes agregar por lo menos un número para calcular resultados.", "ERROR", HEIGHT);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtAgregar;
    // End of variables declaration//GEN-END:variables

}
